root = "."
tmp_dir = ".tmp"

[build]
cmd = "make build"
bin = "./bin/gdns"
include_ext = ["go", "html", "css", "js"]
exclude_dir = ["web/node_modules", ".tmp", "bin"]
delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
