version: "3.9"
services:
  dnsmon:
    image: ghcr.io/t0mer/dnsmon:latest
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DNSMON_STORAGE_DRIVER: "sqlite"
      DNSMON_STORAGE_DSN: "file:/data/dnsmon.db?cache=shared&_fk=1"
      DNSMON_CACHE_DRIVER: "memory"
      DNSMON_LOG_FORMAT: "json"
    volumes:
      - dnsmondata:/data
    restart: unless-stopped

volumes:
  dnsmondata:
